In [1]:
import pandas as pd
dict_data = {
    "c1" : ["a", "a", "b", "a", "b"],
    "c2" : [1, 1, 1, 2, 2],
    "c3" : [1, 1, 2, 2, 2]
}

df = pd.DataFrame(dict_data)
print(df)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [3]:
df_dup_first = df.duplicated()
df_dup_first

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [4]:
df_dup_last = df.duplicated(keep="last")
df_dup_last

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [5]:
df_dup_false = df.duplicated(keep=False)
df_dup_false

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [7]:
col_dup = df["c2"].duplicated()
col_dup

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [8]:
col_dup2 = df.duplicated(subset=["c2"])
col_dup2

0    False
1     True
2     True
3    False
4     True
dtype: bool

In [9]:
# 중복데이터 제거
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [13]:
df2 = df.drop_duplicates()
df2

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [14]:
df3 = df.drop_duplicates(keep="last")
df3

  c1  c2  c3
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [15]:
df4 = df.drop_duplicates(keep=False)
df4

  c1  c2  c3
2  b   1   2
3  a   2   2
4  b   2   2

In [16]:
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [18]:
df5 = df.drop_duplicates(subset=["c2", "c3"])
df5

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

In [19]:
df6 = df.drop_duplicates(subset=["c2", "c3"], keep=False)
df6

  c1  c2  c3
2  b   1   2