In [1]:
import pandas as pd

In [4]:
fruit_names = pd.Series([
    "Apple", "Banana", "Cherry"
])

print(fruit_names)

0     Apple
1    Banana
2    Cherry
dtype: str

In [3]:
pd.Series([
    "Apple", "Banana", "Cherry"
], dtype="string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [6]:
pd.Series([
    "Apple", "Banana", "Cherry"
], dtype=pd.StringDtype())

0     Apple
1    Banana
2    Cherry
dtype: string

In [8]:
fruit_names.astype("string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [3]:
# 문자열 매서드

import pandas as pd
import numpy as np

ser = pd.Series([
    "Apple_사과", "Banana_바나나", "Cherry_체리", np.nan
], index=["Frist ", " Second", " Third", "Fourth"])

print(ser)

ser2 = pd.Series([
    "Apple_사과", "Banana_바나나", "Cherry_체리", np.nan
], index=["Frist ", " Second", " Third", "Fourth"], dtype="string")

print(ser2)

Frist        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth            NaN
dtype: str
Frist        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth           <NA>
dtype: string

In [13]:
print(ser.str.lower())
print(ser.str.upper())
print(ser.str.len())

Frist        apple_사과
 Second    banana_바나나
 Third      cherry_체리
Fourth            NaN
dtype: str
Frist        APPLE_사과
 Second    BANANA_바나나
 Third      CHERRY_체리
Fourth            NaN
dtype: str
Frist       8.0
 Second    10.0
 Third      9.0
Fourth      NaN
dtype: float64

In [15]:
result1 = ser.str.split("_")
result1

Frist        [Apple, 사과]
 Second    [Banana, 바나나]
 Third      [Cherry, 체리]
Fourth               NaN
dtype: object

In [16]:
result2 = ser.str.split("_", expand=True)
print(result2)

              0    1
Frist     Apple   사과
 Second  Banana  바나나
 Third   Cherry   체리
Fourth      NaN  NaN

In [18]:
print(ser.str.split("_").str.get(0))

Frist       Apple
 Second    Banana
 Third     Cherry
Fourth        NaN
dtype: object

In [21]:
# 문자열 매서드

idx = ser.index

print(idx)
print(idx.str.strip())

Index(['Frist ', ' Second', ' Third', 'Fourth'], dtype='str')
Index(['Frist', 'Second', 'Third', 'Fourth'], dtype='str')

In [22]:
print(ser.str.replace("_", ";", regex=False))

Frist        Apple;사과
 Second    Banana;바나나
 Third      Cherry;체리
Fourth            NaN
dtype: str

In [4]:
ser.str.replace("[^a-zA-Z\s]", "", regex=True)

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\KDS-22\AppData\Local\Temp\ipykernel_2752\3217377679.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  ser.str.replace("[^a-zA-Z\s]", "", regex=True)

Frist       Apple
 Second    Banana
 Third     Cherry
Fourth        NaN
dtype: str

In [5]:
print(ser.str[0])

Frist        A
 Second      B
 Third       C
Fourth     NaN
dtype: str

In [6]:
ser.str[0:4]

Frist      Appl
 Second    Bana
 Third     Cher
Fourth      NaN
dtype: str

In [7]:
ser.str.contains("A", na=False)

Frist       True
 Second    False
 Third     False
Fourth     False
dtype: bool

In [8]:
ser.str.contains(r"[A|B][a-z]*")

Frist       True
 Second     True
 Third     False
Fourth     False
dtype: bool

In [9]:
ser.str.fullmatch(r"[A|B][a-z]*")

Frist      False
 Second    False
 Third     False
Fourth     False
dtype: bool

In [14]:
ser3 = pd.Series([
    "a1", "b2", "c3", "d4a5", "e6e7", "f8"
], dtype="string")

print(ser3)

0      a1
1      b2
2      c3
3    d4a5
4    e6e7
5      f8
dtype: string

In [15]:
ser3.str.extractall(r"(\d)").groupby(level=0).agg("".join)

    0
0   1
1   2
2   3
3  45
4  67
5   8

In [17]:
ser3.str.extractall(r"([a-z])").groupby(level=0).agg("".join)

    0
0   a
1   b
2   c
3  da
4  ee
5   f

In [19]:
# 숫자랑 필드랑 컬럼으로 분리

ser3.str.extract(r"(?P<Letter>[a-z]+)(?P<Digit>\d+)")

  Letter Digit
0      a     1
1      b     2
2      c     3
3      d     4
4      e     6
5      f     8